### ISSUE TITLE
Replace or Remove Google Analytics Script

### ISSUE THREAD

**Issue by cognocoder** [melhor-saude/coniventes#1]
Hello, thanks for the fork!

Can you, please, remove or replace the Google Analytics Script from the file index.html? It is used to track number of users. Below, the code slice:
```
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-166337965-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag() { dataLayer.push(arguments); }
  gtag('js', new Date());
  gtag('config', 'UA-166337965-1');
</script>
```

Sorry for the issue, I was unnable to do a pull request since this repository is a fork.

Thanks in advance,
cognocoder

**Comment by enieber** [comment]
@cognocoder sorry for that, the google analytics is removed, thanks
